### ISSUE TITLE
[SST-182] Secrets support Secret Manager in addition to SSM

### ISSUE THREAD

**Issue by fwang** [sst/sst#2954]
**Todo**

* [ ] constructs — Allow specifying source when creating Secret
  `new Config.Secret(stack, "RDS_DB", { source: "secret_manager" });`
* [ ] constructs — Allow overriding Secret Manager prefix path in `sst.config.ts`, similar to `ssmPrefix`
* [ ] cli — `sst bind` supports loading secrets from Secret Manager
* [ ] cli — `sst secrets` supports loading/setting secrets from Secret Manager
* [ ] node — load secrets from Secret Manager

---

Requests

* AdrianK [https://discord.com/channels/983865673656705025/1100504024328974419/1100504024328974419](https://discord.com/channels/983865673656705025/1100504024328974419/1100504024328974419)

<sub>From [SyncLinear.com](https://synclinear.com) | [SST-182](https://linear.app/sst-dev/issue/SST-182/secrets-support-secret-manager-in-addition-to-ssm)</sub>

**Comment by adrianisk** [comment]
Thanks @fwang! I think this all makes sense, but I do have one question regarding the prefix path, and the construct identifier. Our existing secrets follow an enforced path convention: `<environment>/<product>/<resource>/<secret_id>`, so we might have secrets like:

```
prod/our_product/postgres/admin_username
prod/our_product/postgres/admin_password
prod/our_product/kafka/kafka_connect_rw_username
prod/our_product/kafka/kafka_connect_rw_password
```

In this case, if we set the Secret Manager prefix to `prod/our_product`, the ID of the `Config.Secret` construct would need to be `postgres/admin_username` which isn't a valid construct ID (I think?). What are your thoughts on doing all of the above work, but also adding the optional `absolutePath` config option we discussed in the Discord thread? So something like

```
new Config.Secret(stack, "DB_ADMIN_PASSWORD", { source: "secret_manager", absolutePath: "prod/our_product/postgres/admin_password" });
```
